name: Logging

on:
  pull_request_target:
      
jobs:
  legit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"
  nothing:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - run: echo "nothuing"
