name: Logging

on:
  workflow_dispatch:
      
jobs:
  legit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "legit"
  nothing:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - run: echo "nothuing"
